version: '3.8'
services:
  gateway:
    image: ghcr.io/neon-js/ogngatewaynet:main
    # build: # Uncomment to use self built
    #  context: ../src
    #  dockerfile: ../docker/Dockerfile
    environment:
      # - GatewayOptions:EventsOnly=
      # - GatewayOptions:MinimalAltitude=
      # - GatewayOptions:MinimalSpeed=
      # - GatewayOptions:Workers=
      # - GatewayOptions:IntervalSeconds=
      # - GatewayOptions:MaxAgeSeconds=
      # - AprsConfig:AprsPort=
      # - AprsConfig:AprsUser=
      # - AprsConfig:AprsPassword=
      # - AprsConfig:AprsHost=
      # - AprsConfig:DdbAircraftListUrl=
      # - AprsConfig:FilterPosition:Latitude=
      # - AprsConfig:FilterPosition:Longitude=
      # - AprsConfig:FilterRadius=
    restart: unless-stopped
  frontend:
    image: nginx:latest
    volumes:
      - ../src/frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - gateway
    restart: unless-stopped
